sudo: required
dist: trusty
group: edge
language: c
services:
  - docker
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
# https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
before_cache:
- >
  mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
  | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
before_install:
# https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
- if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
- ci/before_install.sh
script:
- ci/script.bash
# https://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key:
    secure: aOrH7O44if7TdnSOuvsnjCO5m8v1JFxp/y4MWABEwc6NlK3WoJtpW+aF2guaps3RX7C7gMenhC7BQ3E3LjWvceH8h1d6D5Mm53RM9GVnpIckCyp5vwADeMBL3wR6Xlr5xMub7QwSNeZbLWORM9GqYATB+vKhp/dmUlWbQOhlZsRkoPQKUWjK7LXCLu3qJp39oZBrsfZuhWXNhBZvyeMJOOycpXoPVVWqp+nAop5dSYXLHWUY3l/XR40oBd6HxvWXzfjlQkmqBkZKfQZ0wvwzrB/6k48Z+8CTQa1cbC5obBB8gAwbhJF2w06LPP8+LI+BnGwVRrQh7cCmmFQ7hxW41a2IFi5Ar0Gsuei5eGq/nzwp3i5LRKLHKJvVEOENOpRESC8dZCu2Cq8oTBJIFTUx97rVBESwwbOiNfowheKqu7hocuvQP1kJ3DXqinUig1+Df3+J8AGhKgBMaRpFYYU4NwpFkSllE3KqFPuu+5YV82/BWezEpKcawqu/ZhnGUp4TpZJe69y8tPvu9OYP2p6aTbDhLnczs3+tdx6K0+qNZBXcY+aMvMy9vTtiSqXlsb2kSo/xCEQ1S9owL56tdI1Ux8pDQm46b69IgHJRJ4sNOB26P5fLfDTMXhNIIsIPtGmAmHfMi3GanZ6UQX9e8wxu4GT69o1xopkmvDBztIMkg6Q=
  file: resizedisk_linux_amd64.tar.gz
  skip_cleanup: true
  on:
    repo: shokohara/haskell-gcp-resizedisk
