name: worker
ghc-options:
    - -Wall
library:
  source-dirs:
    - src
executables:
  worker:
    main: app/Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - worker
      - optparse-applicative
tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
    dependencies:
      - hspec
      - worker
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types
dependencies:
  - base
  - servant
  - servant-server
  - servant-client
  - either
  - http-client
  - transformers
  - process
  - aeson
  - text
  - aeson-casing
  - wai
  - warp
  - transformers
  - wai-logger
  - async
  - here
  - stm

