name: traceinstances
ghc-options:
    - -Wall
library:
  source-dirs:
    - src
executables:
  traceinstances:
    main: app/Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - traceinstances
      - optparse-applicative
tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
    dependencies:
      - hspec
      - traceinstances
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types
dependencies:
  - base
  - servant
  - servant-server
  - servant-client
  - either
  - http-client
  - transformers
  - aeson
  - wai
  - warp
  - transformers

