name: subscriber
ghc-options:
    - -Wall
library:
  source-dirs:
    - src
executables:
  subscriber:
    main: app/Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - subscriber
      - optparse-applicative
tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
    dependencies:
      - hspec
      - subscriber
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types
dependencies:
  - base
  - async
  - servant
  - servant-server
  - servant-client
  - either
  - http-client
  - transformers
  - process
  - aeson
  - text
  - aeson-casing
  - wai
  - warp
  - transformers
  - wai-logger
  - async
  - here
  - containers
  - stm
  - mtl
  - stm-containers
  - classy-prelude
  - directory
  - resourcet
  - lens
  - gogol
  - gogol-storage
  - conduit
  - conduit-extra
  - extra
  - filepath
  - regex-posix
  - regex-tdfa

